/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package akuntansi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COMPUTER
 */
public class frmInventoryValue extends javax.swing.JFrame {

    Connection conn;

    /**
     * Creates new form frmInventoryValue
     */
    public frmInventoryValue(Connection conn) {
        this.conn = conn;
        initComponents();
        loadAllDatabase();
        setLocationRelativeTo(null);
    }

    private void loadAllDatabase() {
        removeTableData();
        try {
            String sql = "select s.nama_produk, s.harga_beli, s.stock_awal, iv.masuk, iv.keluar, s.stock "
                    + "from stock s inner join inventory iv on s.kode_produk = iv.kode_produk;";
            PreparedStatement pstatement = conn.prepareStatement(sql);

            ResultSet rs = pstatement.executeQuery();
            if (rs.isBeforeFirst()) { // check is resultset not empty
                while (rs.next()) {
                    DefaultTableModel tableModel = (DefaultTableModel) tblStock1.getModel();
                    double harga = rs.getDouble("harga_beli");
                    double value = 0;
                    int stock = rs.getInt("stock");
                    value = stock * harga;
                    Object data[] = {
                        rs.getString("nama_produk"),
                        harga,
                        rs.getInt("stock_awal"),
                        rs.getInt("masuk"),
                        rs.getInt("keluar"),
                        stock,
                        value
                    };
                    tableModel.addRow(data);
                }
                totalStockAwal();
                totalIn();
                totalOut();
                totalStockAkhir();
                totalValue();
            } else {
                util.Sutil.msg(this, "Record Empty");
            }

            rs.close();
            pstatement.close();

        } catch (SQLException ex) {
            Logger.getLogger(frmInventoryValue.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStock1 = new javax.swing.JTable();
        txtStockAwal = new javax.swing.JTextField();
        txtIn = new javax.swing.JTextField();
        txtOut = new javax.swing.JTextField();
        txtStockAkhir = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Search : ");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStock1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Produk", "Harga", "Stock Awal", "In", "Out", "Stock Akhir", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStock1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tblStock1);
        tblStock1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        txtStockAwal.setEnabled(false);

        txtIn.setEnabled(false);

        txtOut.setEnabled(false);

        txtStockAkhir.setEnabled(false);

        txtValue.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 224, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(txtStockAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtStockAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchbyName();


    }//GEN-LAST:event_btnSearchActionPerformed

    private int totalStockAwal() {
        int stockawal = 0;
        for (int i = 0; i < tblStock1.getRowCount(); i++) {

            stockawal += Integer.valueOf(tblStock1.getValueAt(i, 2).toString());
            txtStockAwal.setText(String.valueOf(stockawal));
        }
        return stockawal;
    }

    private double totalIn() {
        double in = 0;
        for (int i = 0; i < tblStock1.getRowCount(); i++) {

            in += Double.valueOf(tblStock1.getValueAt(i, 3).toString());
            txtIn.setText(String.valueOf(in));
        }
        return in;
    }

    private double totalOut() {
        double out = 0;
        for (int i = 0; i < tblStock1.getRowCount(); i++) {

            out += Double.valueOf(tblStock1.getValueAt(i, 4).toString());

            txtOut.setText(String.valueOf(out));
        }
        return out;
    }

    private int totalStockAkhir() {
        int stockakhir = 0;
        for (int i = 0; i < tblStock1.getRowCount(); i++) {

            stockakhir += Integer.valueOf(tblStock1.getValueAt(i, 5).toString());

            txtStockAkhir.setText(String.valueOf(stockakhir));
        }
        return stockakhir;
    }

    private double totalValue() {
        double value = 0;
        for (int i = 0; i < tblStock1.getRowCount(); i++) {

            value += Double.valueOf(tblStock1.getValueAt(i, 6).toString());

            txtValue.setText(String.valueOf(value));
        }
        return value;
    }

    private void searchbyName() {
        try {
            removeTableData();
            String sql = "select s.nama_produk, s.jumlahpembelian, iv.masuk, iv.keluar, s.stock from stock s "
                    + "inner join inventory iv on s.kode_produk = iv.kode_produk WHERE nama_produk like ?";

            PreparedStatement pstatement = conn.prepareStatement(sql);
            pstatement.setString(1, "%" + txtSearch.getText().trim() + "%");

            ResultSet rs = pstatement.executeQuery();
            if (rs.isBeforeFirst()) { // check is resultset not empty
                DefaultTableModel tableModel = (DefaultTableModel) tblStock1.getModel();

                while (rs.next()) {
                    int harga = 0;
                    int value;
                    int stock = rs.getInt("stock");
                    value = stock * harga;
                    Object data[] = {
                        rs.getString("nama_produk"),
                        harga,
                        rs.getInt("jumlahpembelian"),
                        rs.getInt("masuk"),
                        rs.getInt("keluar"),
                        rs.getInt("stock"),
                        value
                    };
                    tableModel.addRow(data);
                }
            }

            rs.close();
            pstatement.close();
        } catch (SQLException ex) {
            System.out.println("Error:\n" + ex.getLocalizedMessage());
        }
    }

    public void passData() {
        frmProfitLoss fpl = new frmProfitLoss(conn);
        fpl.endingvalue = Integer.valueOf(txtValue.getText());
        fpl.setVisible(true);
    }

    private void removeTableData() {
        DefaultTableModel tableModel = (DefaultTableModel) tblStock1.getModel();
        tableModel.setRowCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStock1;
    private javax.swing.JTextField txtIn;
    private javax.swing.JTextField txtOut;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStockAkhir;
    private javax.swing.JTextField txtStockAwal;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
